AWSTemplateFormatVersion: "2010-09-09"
Description: AWS EC2 for SSH Cloud9 Env to experiment Deep Learning with ElasticIP, Security Group, and EC2 Key pair

Parameters:
  ImageId:
    Description: Amazon Machine Image (AMI)
    Type: String
    Default: ami-06c414f3ba4a59e2f

  EC2InstanceType:
    Description: EC2 instance type on which IDE runs
    Type: String
    Default: g4dn.xlarge

  VolumeSize:
    Description: root volume size
    Type: String
    Default: 100

  KeyName:
    Description: Keypair name
    Type: String
    Default: my-key

  SubnetId:
    Description: Public subnet in vpc (For example, check your pucblic-subnet ip in default vpc.)
    Type: String
    Default: subnet-XXXXXXXXXXXXXXXXX

  EC2IAMInstanceProfile:
    Description: IAM Instance Profile
    Type: String
    Default: arn:aws:iam::XXXXXXXXXXXX:instance-profile/existing-role-profile

Resources:
  # EC2 Key pair
  NewKeyPair:
    Type: "AWS::EC2::KeyPair"
    Properties:
      KeyName: !Ref "KeyName"
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-key"

  # Security Group
  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: for remote development
      GroupName: !Sub "${AWS::StackName}-sg"
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          FromPort: -1
          IpProtocol: -1
          ToPort: -1
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-sg"

  # EC2 Instance
  Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      ImageId: !Ref "ImageId"
      InstanceType: !Ref "EC2InstanceType"
      KeyName: !Ref "NewKeyPair"
      SecurityGroupIds:
        - !GetAtt [Ec2SecurityGroup, GroupId]
      SubnetId: !Ref "SubnetId"
      IamInstanceProfile: !Ref "EC2IAMInstanceProfile"
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp3
            VolumeSize: !Ref "VolumeSize"
            DeleteOnTermination: "true"
            Encrypted: "false"
      Tags:
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-ec2"
